### ISSUE TITLE
Running this tool via command line causes it to press enter

### ISSUE THREAD

**Issue by Darkblader24** [Shadsterwolf/BotWUnpacker#10]
Running this tool via command line causes it to press enter. This means that running this script in large batches makes my PC spam the "Enter" key. This messes with all sorts of stuff while I'm using other apps in the meantime.
Please fix this, thank you!

**Comment by Shadsterwolf** [comment]
I believe in Program.cs line 38 is causing the issue. 
I forget why I even passed that enter key

**Comment by Darkblader24** [comment]
Yup that's it. I have removed that line and now it works fine.

**Comment by Shadsterwolf** [comment]
Issue now resolved in 5.0.1
