### ISSUE TITLE
env.sgenvb

### ISSUE THREAD

**Issue by frykillr** [Shadsterwolf/BotWUnpacker#2]
Hi,

i made a test and found out that the unpacker has a problem with YAZ0 encoding.

with this file (env.sgenvb) the game gets a breaking sky.
even on unmodded files inside that file it still breaks.
he is a zip file of the original and repacked (With unedited files) BOTW 1.5.0 DLC3.0 (to be precise)

is it possible to check where is the problem in this please?

[env.sgenvb.zip](https://github.com/Shadsterwolf/BotWUnpacker/files/1790609/env.sgenvb.zip)

**Comment by Shadsterwolf** [comment]
Per our conversations on Discord (posting my research),

I believe this is a new rule that calculates the padding for special cases, such as this one which is included in the Bootup.pack 

From what I see from the original data... 
Every node's data ending offset MUST end with 
0, 4, 8, or C (12).
If the data ends with 4 or C, add additional 4 padding
If the data ends with 0 or 8, do not add padding

Another case is this fixed data offset... (00 00 20 00)
It appears to space the nodes further away for some reason.
So it appears to break for the starting group at offset 0x2000
Then after every 20 nodes to space them to the next offset that is divisible by 2000
(2000, 4000, 6000, 8000, A000, C000, E000 - just a guess for now)
