### ISSUE TITLE
BotwUnpacker needs an equivalent to 'sarc update' on Python

### ISSUE THREAD

**Issue by ghost** [Shadsterwolf/BotWUnpacker#4]
Python has a tool by leoetlino#1857 simply called sarc, obtainable with the command `pip install sarc`

With it you can update a sarc archive without having to build a new one from scratch using the command `sarc update`. This is ideal particularly for archives like `Title.pack` which will display a lot of distortion on the title screen if they're not in the mysterious Goldilocks zone.

I can provide you with files to test this with but I would need your Discord or email or something because it's a title screen pack I made for myself that I cannot redistribute because I'm lacking permission from artists.

**Comment by Shadsterwolf** [comment]
You can catch me on Discord 
> Shadsterwolf#1602
