### ISSUE TITLE
Is this only for WiiU version? 

### ISSUE THREAD

**Issue by masagrator** [Shadsterwolf/BotWUnpacker#6]
I try to unpack files from Switch BotW with patch v720896 and it can't unpack any *.pack files. 

Extraction Error:
Unknown SARC header (Byte Order Mark 0x06)

First 8 bytes are always
53 41 52 43 14 00 FF FE

Decoding yaz0 works without issue.

**Comment by masagrator** [comment]
One of the examples

[Bootup_EUen.zip](https://github.com/Shadsterwolf/BotWUnpacker/files/2799433/Bootup_EUen.zip)

**Comment by Shadsterwolf** [comment]
Correct, only for Wii U for now. I dont have support for switch version. (I have a modded switch but haven't been successful in dumping the game files)

**Comment by masagrator** [comment]
I can pack tools with cmd batches for unpacking NSP game and update, if you want. 
I want to translate this game and only obstacle is unpacking/packing *.pack files

**Comment by Shadsterwolf** [comment]
Thanks for the sample, if you have another one, that would help. 
A dungeon.pack or something

**Comment by masagrator** [comment]
Here you go.
[Dungeon000.zip](https://github.com/Shadsterwolf/BotWUnpacker/files/2803184/Dungeon000.zip)

**Comment by masagrator** [comment]
Is there any progress or "life" and no time for now? :P

**Comment by Shadsterwolf** [comment]
It's in progress, I got extraction working fine, next is build. Just a lot on the to-do list.

**Comment by Shadsterwolf** [comment]
Switch support I believe is now ready
https://github.com/Shadsterwolf/BotWUnpacker/releases

Give the UI a try, console support will come later.

**Comment by TROguz** [comment]
Please add bffnt fonts unpack and repack. I want to edit fonts and translate zelda games.
