### ISSUE TITLE
how to run this code? I can't find .exe

### ISSUE THREAD

**Issue by lonioi314** [Shadsterwolf/BotWUnpacker#7]
I don't find .exe. how can I start to use it?

**Comment by Shadsterwolf** [comment]
https://github.com/Shadsterwolf/BotWUnpacker/releases
Click on a **Version**, you'll see a zip file to download under **Assets**
Right-click and extract the zip, and you'll find the .exe in there.

I know github can be confusing for new people,
_So when you see "Clone or Download" that just means the source code._
Slightly above that is a navigation bar, and "**Releases**" is the one you want to click on which is where I already compiled the code for you into a working .exe

As for how to use it, you can read more here:
https://github.com/Shadsterwolf/BotWUnpacker/blob/master/README.md
I cannot provide the game files to you for legal reasons, 
The fellas at the Zelda Modding community discord can help you too: https://discord.gg/NzHApcX
